name: Remove Suppressed SARIF Findings
description: This action removes findings from the SARIF file that have suppressions applied.
inputs:
  input-file:
    description: path to the unfiltered SARIF file
    required: false
    default: '../output'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/remove-suppressed-findings.sh "${{ inputs.input-file }}" "${{ inputs.output-file }}"
      shell: bash
